////////////////////////////////////////////////////////////////
//                                                            //
//  DO NOT EDIT THIS FILE -- WRITE YOUR FUNCTIONS IN  tp4.c   //
//                                                            //
////////////////////////////////////////////////////////////////

// Reads the contents of "tp4.c", ignoring any main() function,
#define main no__main
#include "tp4.c"
#undef main

#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <time.h>
#include <string.h>
#include <errno.h>
#include <inttypes.h>
#include <assert.h>

struct xx_ranctx { uint32_t a; uint32_t b; uint32_t c; uint32_t d; } xx_ranc;

uint32_t xx_ranval()
{
#define rot(x, k) (((x) << (k)) | ((x) >> (32 - (k))))
  uint32_t e = xx_ranc.a - rot(xx_ranc.b, 27);
  xx_ranc.a = xx_ranc.b ^ rot(xx_ranc.c, 17);
  xx_ranc.b = xx_ranc.c + xx_ranc.d;
  xx_ranc.c = xx_ranc.d + e;
  xx_ranc.d = e + xx_ranc.a;
  return xx_ranc.d;
}

void xx_raninit(uint32_t seed)
{
  xx_ranc.a = 0xf1ea5eed, xx_ranc.b = xx_ranc.c = xx_ranc.d = seed;
  for (uint32_t i = 0; i < 20; ++i)
    (void) xx_ranval();
}

FILE* xx_trace;
const char* xx_trace_name;

void xx_trace_init(const char* name)
{
  xx_trace_name = getenv("OUTPUT");
  if (!xx_trace_name)
    {
      static char tmp[30];
      strncpy(tmp, name, 30);
      strncat(tmp, ".trace", 30);
      xx_trace_name = tmp;
    }
  xx_trace = fopen(xx_trace_name, "w+");
  if (!xx_trace)
    {
      fprintf(stderr, "cannot open '%s' for writing: %s\n",
	      xx_trace_name, strerror(errno));
      exit(2);
    }

  time_t rawtime = time(NULL);
  struct tm *timeinfo = gmtime(&rawtime);
  char buffer[20];
  strftime(buffer, 80, "%F %T%n", timeinfo);

  int u = getuid();
  int r = rawtime & 0xffffff;
  fprintf(xx_trace, "%s\n%d\n%d\n", name, u, r);
  fputs(buffer, xx_trace);
  u ^= r;
  const char* s = getenv("SEED");
  if (s)
    u = atoi(s);
  xx_raninit(u);
}

void xx_trace_done()
{
  fclose(xx_trace);
  printf("please submit '%s'\n", xx_trace_name);
}

int xx_cmp(int a, int b)
{
  if (((a&1) == 0) && ((b&1) == 1))
    return -1;
  if (((a&1) == 1) && ((b&1) == 0))
    return 1;
  if (a < b)
    return -1;
  return a > b;
}

void xx_fisher_yates_shuffle(int* tab, unsigned count)
{
  unsigned i = count;
  while (i)
    {
      unsigned j = xx_ranval() % i--;
      int tmp = tab[i];
      tab[i] = tab[j];
      tab[j] = tmp;
    }
}

// Make sure v is at a position >= j, unless  j == l+1
unsigned xx_fixup_partition(int* tab, unsigned l, unsigned j, unsigned r,
			    int v, int (*cmp)(int a, int b))
{
  (void) cmp;
  if (tab[j] == v || j == l + 1)
    return j;
  unsigned i = l;
  while (tab[i] != v)
    {
      ++i;
      assert(i < r);
    }
  assert(i != j);
  if (i > j)
    return j;
  --j;
  assert(j > 0);
  int tmp = tab[j];
  tab[j] = tab[i];
  tab[i] = tmp;
  return j;
}

void xx_scan_partition(int* tab, unsigned l, unsigned r,
		       int v, int (*cmp)(int a, int b))
{
  for (unsigned i = l; i < r; ++i)
    {
      int res = cmp(tab[i], v);
      fputc((res <= 0) ? '<' : '>', xx_trace);
    }
  fputc('\n', xx_trace);
}

int main()
{
#if Q == 1
  xx_trace_init("tp4q1");
  const unsigned asize = 42;
  int a[asize];
  for (unsigned i = 0; i < asize; ++i)
    a[i] = i;
  xx_fisher_yates_shuffle(a, asize);
  for (unsigned i = 0; i < asize; ++i)
    {
      int b[asize];
      memcpy(b, a, sizeof(a));
      unsigned j = partition_cmp(b, 0, asize, i, xx_cmp);
      j = xx_fixup_partition(b, 0, j, asize, a[i], xx_cmp);
      fprintf(xx_trace, "%2u: ", j);
      xx_scan_partition(b, 0, asize - 1, a[i], xx_cmp);
    }
  for (unsigned i = 0; i < asize; ++i)
    a[i] = 0;
  for (unsigned i = 0; i < asize; i += 10)
    {
      unsigned j = partition_cmp(a, 0, asize, i, xx_cmp);
      assert(j < asize);
    }
  xx_trace_done();
#elif Q == 2
  xx_trace_init("tp4q2");
  const unsigned asize = 42;
  int a[asize];
  for (unsigned i = 0; i < asize; ++i)
    a[i] = i;
  xx_fisher_yates_shuffle(a, asize);
  for (unsigned i = 1; i < 14; ++i)
    {
      print_int_array(xx_trace, a, i);
      fprintf(xx_trace, "median3 (custom cmp) at %u\n",
              pivot_median3(a, 0, i, xx_cmp));
    }
  xx_trace_done();
#elif Q == 3
  xx_trace_init("tp4q3");
  const unsigned asize = 5000;
  int a[asize];
  for (unsigned i = 0; i < asize; ++i)
    a[i] = ((int) xx_ranval()) % (int) asize;
  quick_sort_cmp(a, asize, pivot_median3, xx_cmp);
  print_int_array(xx_trace, a, 100);
  quick_sort_cmp(a, asize, pivot_rand, xx_cmp);
  print_int_array(xx_trace, a + asize/2 - 50, 100);
  quick_sort_cmp(a, asize, pivot_first, xx_cmp);
  print_int_array(xx_trace, a + asize - 100, 100);
  for (unsigned i = 0; i < asize; ++i)
    a[i] = 33;
  quick_sort_cmp(a, asize, pivot_median3, xx_cmp);
  quick_sort_cmp(a, asize, pivot_first, xx_cmp);
  print_int_array(xx_trace, a, 10);
  print_int_array(xx_trace, a + asize - 10, 10);
  xx_trace_done();
#else
  puts("Compile with -DQ=n, where n is the question number.");
#endif
  return 0;
}
